### ISSUE TITLE
No `version` or `--help` output from windows browsers

### ISSUE THREAD

**Issue by caspervonb** [caspervonb/node-browser_process#7]
```sh
$ chrome.exe --version
# no output, instead the browser is launched.
```
```sh
$ firefox --version
# no output, no launch.
```

Which breaks the new behavior of `type` introduced in b7806a1f201921eb717c66b0488339b6533aee90

**Comment by stereokai** [comment]
Will have a look when I'm home. Where is the code that calls this?

**Comment by caspervonb** [comment]
It's in `type` which yields the type of the browser, https://github.com/caspervonb/node-browser_process/blob/master/lib/index.js#L74

Troubleshooting is doable from just a cmd shell tho.

**Comment by stereokai** [comment]
Got it. Will look at it later.

**Comment by caspervonb** [comment]
Firefox does pass the tests tho so it's not an issue as it works fine, I'm just not getting it to print to stdout in a `cmd.exe` for whatever reason which is a bit of a `what the hell is going on here` moment but i'll just write it up to my inexperience with the cmd shell.

**Comment by stereokai** [comment]
Have you tried Powershell?

**Comment by caspervonb** [comment]
Yeah same deal.

**Comment by stereokai** [comment]
I don't know yet. I'll have a look at home. Do you have the latest Chrome?

**Comment by caspervonb** [comment]
> Do you have the latest Chrome?
How can I test the version? :grinning:

But same results with both chrome and chromium, latest'ish (44 or so).

Noticing that the executable behaves differently than on unix, on mac and linux the executable is blocking, killing it will kill the tab.

On windows, it just returns immediately.

**Comment by stereokai** [comment]
You can check in Chrome -> About.

That's weird, when I terminated amok, my chrome quitted.

**Comment by caspervonb** [comment]
> You can check in Chrome -> About.

I know, just found it amusing in an issue about `--version` not working :smile:
Based on the folder names its 45.0.0.2442.0.

**Comment by stereokai** [comment]
Yeah :D

Alright so I'll have a look when I'm home.

**Comment by stereokai** [comment]
@caspervonb I got you covered bro.

`chrome --version` flag/switch is not supported on Windows: https://code.google.com/p/chromium/issues/detail?id=158372

But when there's a will, there's a way. The version number is stored in the registry in the uninstall information. So we can query it via the command line, as per the example in the above link:

`reg query "HKEY_CURRENT_USER\Software\Microsoft\Windows\CurrentVersion\Uninstall\Google Chrome" /v DisplayVersion`

However, this did not work for me. The reason being - the key does not exist. My immediate assumption was that in the 2 years since this idea was suggested, Google has released the 64bit version of Chrome, so, a registry scour was in order. Eventually I have found my target:

`reg query "HKEY_LOCAL_MACHINE\SOFTWARE\Wow6432Node\Microsoft\Windows\CurrentVersion\Uninstall\Google Chrome" /v DisplayVersion`

Which outputs:
```
DisplayVersion    REG_SZ    44.0.2403.125
```

Which you can parse with a regex to get the version number. To strike out all possible fail points, I suggest you check the original 32bit query on a 32bit Chrome installatation - and in your code, you could try one and if it fails, try the other. They are bound to succeed, because this information must be in the registry - unless someone is using Chrome in a hackish portable way, and I don't even know if that is even possible or something you should care about.

**Comment by caspervonb** [comment]
All right that's a shame, was hoping of using --version as an agnostic way to identify the browser name and version without resolving to platform specific things like the registry.

Think I'll revert to just using the basename of the default paths for matching the `type`, otherwise it'll become too complex with branching logic etc when it should just be a simple lookup.

For `detect`, which is yet to be implemented however this is gold :+1:, need to report browser name, type, version, path, etc.

**Comment by stereokai** [comment]
Well, I'm happy I could help with something..

**Comment by caspervonb** [comment]
Rebased a little on master, I know I know but with 0 forks and 0 current branches its fine, *really*.

Now if the executable name is the default one, it'll figure out the type but, there are failures which the commit was supposed to fix which is things like `Google\ Chrome\ Canary` which is the executable name of canary on OS X.

But, separate issue.

Thanks for the digging @stereokai :grinning:

**Comment by stereokai** [comment]
F***ing A man :)
